name: Build and Release

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Zipfile
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r blended_save_to_dxf-${{ env.RELEASE_VERSION }}.zip .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Update version
          draft: false
          prerelease: false
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: blended_save_to_dxf-${{ env.RELEASE_VERSION }}.zip
          asset_name: blended_save_to_dxf-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
